// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:recipes/data/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CommentAdapter());
    registerAdapter(IngredientAdapter());
    registerAdapter(MeasureUnitAdapter());
    registerAdapter(RecipeAdapter());
    registerAdapter(RecipeIngredientAdapter());
    registerAdapter(RecipeStepAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CommentAdapter());
    registerAdapter(IngredientAdapter());
    registerAdapter(MeasureUnitAdapter());
    registerAdapter(RecipeAdapter());
    registerAdapter(RecipeIngredientAdapter());
    registerAdapter(RecipeStepAdapter());
  }
}
